name: "Hacktoberfest Issue labeler"
description: "Automatically label issues with 'Hacktober' fest during the month of october and remove it after october 31"
author: "mdb571"
branding:
  icon: tag
  color: purple

inputs:
  github_token:
    description: "GITHUB Token"
    required: true
  label_filter:
    description: "Label Issues having this label only"
    required: true
  
runs:
  using: "docker"
  image: "Dockerfile"